### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by stephane303** [miragejs/miragejs#611]
Your example for the sort function could be misleading, especially if automatic casting or number are used.

https://miragejs.com/api/classes/collection/#sort
```
let postsByTitleAsc = user.posts.sort((a, b) => {
  return b.title < a.title;
})
```

the compare function should return -1, 0 , 1, not a boolean

**Comment by samselikoff** [comment]
Thank you! Fixed in https://github.com/miragejs/miragejs/commit/ac2727a69a4a941e8954a6f36b469372ead829cd.

**Comment by webdevnerdstuff** [comment]
@samselikoff Not sure if anybody noticed, but the webpage is still showing the old example.
